"""Add language column

Revision ID: 128dcbece3d6
Revises: 3a04a7daad9a
Create Date: 2026-04-07 10:00:19.296039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '128dcbece3d6'
down_revision: Union[str, None] = '3a04a7daad9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('language', sa.String(length=10), server_default='ru', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('telegram_accounts', 'language')
    # ### end Alembic commands ###
