"""Initial migration

Revision ID: 3a04a7daad9a
Revises: 
Create Date: 2026-04-04 19:44:35.234111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a04a7daad9a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bhm_branches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bhm_code', sa.String(length=5), nullable=False),
    sa.Column('branch_name', sa.String(length=255), nullable=False),
    sa.Column('region_name', sa.String(length=255), nullable=False),
    sa.Column('city_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bhm_branches_bhm_code'), 'bhm_branches', ['bhm_code'], unique=True)
    op.create_table('telegram_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_accounts_telegram_user_id'), 'telegram_accounts', ['telegram_user_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=512), nullable=False),
    sa.Column('role', sa.Enum('developer', 'reviewer', name='user_role_enum', create_constraint=True), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_login'), 'users', ['login'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fio_original', sa.String(length=512), nullable=False),
    sa.Column('fio_normalized', sa.String(length=512), nullable=False),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['bhm_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employees_fio_normalized'), 'employees', ['fio_normalized'], unique=False)
    op.create_table('inventory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('inventory_code', sa.String(length=64), nullable=False),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('equipment_type', sa.Enum('computer', 'printer', name='equipment_type_enum', create_constraint=True), nullable=False),
    sa.Column('issue_year', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'repair', 'replaced', name='inventory_status_enum', create_constraint=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['branch_id'], ['bhm_branches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inventory_inventory_code'), 'inventory', ['inventory_code'], unique=True)
    op.create_table('requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_number', sa.String(length=32), nullable=False),
    sa.Column('telegram_account_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('employee_fio_snapshot', sa.String(length=512), nullable=False),
    sa.Column('employee_fio_normalized_basic', sa.String(length=512), nullable=False),
    sa.Column('employee_fio_normalized_translit', sa.String(length=512), nullable=False),
    sa.Column('employee_position_snapshot', sa.Text(), nullable=True),
    sa.Column('branch_id', sa.Integer(), nullable=False),
    sa.Column('bhm_code_snapshot', sa.String(length=5), nullable=False),
    sa.Column('branch_name_snapshot', sa.String(length=255), nullable=False),
    sa.Column('request_type', sa.Enum('replacement', 'new_issue', 'repair', name='request_type_enum', create_constraint=True), nullable=False),
    sa.Column('equipment_type', sa.Enum('computer', 'printer', name='equipment_type_enum'), nullable=False),
    sa.Column('inventory_id', sa.Integer(), nullable=True),
    sa.Column('inventory_code_snapshot', sa.String(length=64), nullable=True),
    sa.Column('reason_text', sa.Text(), nullable=True),
    sa.Column('problem_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('new', 'in_progress', 'closed', name='request_status_enum', create_constraint=True), nullable=False),
    sa.Column('final_decision', sa.Enum('pending', 'approved', 'rejected', name='final_decision_enum', create_constraint=True), nullable=False),
    sa.Column('reject_reason', sa.Text(), nullable=True),
    sa.Column('reviewer_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['bhm_branches.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['telegram_account_id'], ['telegram_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_employee_fio_normalized_basic'), 'requests', ['employee_fio_normalized_basic'], unique=False)
    op.create_index(op.f('ix_requests_employee_fio_normalized_translit'), 'requests', ['employee_fio_normalized_translit'], unique=False)
    op.create_index(op.f('ix_requests_request_number'), 'requests', ['request_number'], unique=True)
    op.create_table('request_comments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=255), nullable=False),
    sa.Column('comment_text', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_comments')
    op.drop_index(op.f('ix_requests_request_number'), table_name='requests')
    op.drop_index(op.f('ix_requests_employee_fio_normalized_translit'), table_name='requests')
    op.drop_index(op.f('ix_requests_employee_fio_normalized_basic'), table_name='requests')
    op.drop_table('requests')
    op.drop_index(op.f('ix_inventory_inventory_code'), table_name='inventory')
    op.drop_table('inventory')
    op.drop_index(op.f('ix_employees_fio_normalized'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_telegram_accounts_telegram_user_id'), table_name='telegram_accounts')
    op.drop_table('telegram_accounts')
    op.drop_index(op.f('ix_bhm_branches_bhm_code'), table_name='bhm_branches')
    op.drop_table('bhm_branches')
    # ### end Alembic commands ###
