"""add selected_branch_id to telegram_accounts

Revision ID: 3cd42698dc3c
Revises: e5f6a7b8c9d0
Create Date: 2026-05-13 14:59:50.559784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cd42698dc3c'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('telegram_accounts', sa.Column('selected_branch_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'telegram_accounts', 'bhm_branches', ['selected_branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'telegram_accounts', type_='foreignkey')
    op.drop_column('telegram_accounts', 'selected_branch_id')
    # ### end Alembic commands ###
